# Generated by Django 3.2.3 on 2021-06-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
        migrations.AddField(
            model_name='upload',
            name='user',
            field=models.ManyToManyField(related_name='uploads', to='PhotoApp.User'),
        ),
    ]
