# Generated by Django 3.2.3 on 2021-06-16 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PhotoApp.user'),
        ),
    ]
