# Generated by Django 3.2.3 on 2021-06-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='uploader',
            new_name='user',
        ),
    ]
