# Generated by Django 3.2.3 on 2021-06-12 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0002_rename_uploader_upload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='user',
            field=models.OneToOneField(default='None', on_delete=django.db.models.deletion.CASCADE, to='PhotoApp.user'),
        ),
    ]
