# Generated by Django 3.2.3 on 2021-06-13 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0007_auto_20210612_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='info',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_album', to='PhotoApp.user')),
            ],
        ),
    ]
